import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { redirect, notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import Link from "next/link";
import { 
  Zap, 
  ChevronLeft, 
  Download, 
  Copy, 
  Share2, 
  Layout, 
  Image as ImageIcon,
  MessageSquare,
  Sparkles,
  ExternalLink,
  Wand2,
  CheckCircle2,
  ArrowRight
} from "lucide-react";

export default async function PostViewPage(props: { params: Promise<{ id: string }> }) {
  const { id } = await props.params;
  const session = await getServerSession(authOptions);
  
  if (!session) {
    redirect("/auth/login");
  }

  let post;
  try {
    post = await prisma.post.findUnique({
      where: { 
        id: id,
        userId: session.user.id
      },
    });
  } catch (err) {
    console.error("DB Error:", err);
  }

  if (!post) {
    notFound();
  }

  let content = [];
  try {
    content = JSON.parse(post.content || "[]");
  } catch (err) {
    console.error("JSON Parse Error:", err);
    content = [];
  }

  const isCarousel = post.type === "CAROUSEL";

  return (
    <div className="min-h-screen flex flex-col bg-[#020205] text-white">
      {/* Premium Header */}
      <header className="sticky top-0 z-50 w-full border-b border-white/5 bg-[#020205]/80 backdrop-blur-2xl">
        <div className="container flex h-20 items-center justify-between px-6 mx-auto">
          <div className="flex items-center gap-6">
            <Link 
              href="/dashboard"
              className="h-10 w-10 rounded-xl flex items-center justify-center border border-white/10 bg-white/5 hover:bg-white/10 transition-all hover:scale-105 active:scale-95"
            >
              <ChevronLeft className="h-5 w-5" />
            </Link>
            <div className="hidden md:block">
               <h1 className="font-black text-xl tracking-tighter gradient-text">Picassek Studio</h1>
            </div>
          </div>
          
          <div className="flex items-center gap-6">
            <div className="flex flex-col items-end">
              <span className="text-[10px] font-black uppercase tracking-widest text-white/30">Активный баланс</span>
              <span className="text-lg font-black text-primary">{(session.user as any).balance || 150} ₽</span>
            </div>
            <Link 
              href="/dashboard/create"
              className="px-5 py-2.5 rounded-xl bg-white text-black text-xs font-black uppercase tracking-wider flex items-center gap-2 hover:scale-105 transition-all shadow-xl shadow-primary/10"
            >
              <Plus className="h-4 w-4" />
              Создать еще
            </Link>
          </div>
        </div>
      </header>

      <main className="flex-1 container max-w-7xl px-6 py-12 mx-auto space-y-16">
        {/* Title Section */}
        <section className="space-y-4 text-center max-w-3xl mx-auto">
           <div className="flex justify-center mb-6">
              <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full glass border-white/5 text-[10px] font-black uppercase tracking-[0.2em] text-primary italic">
                 <Sparkles className="h-3.5 w-3.5" />
                 Generated by Picassek AI v4.5
              </div>
           </div>
           <h2 className="text-4xl md:text-5xl font-black tracking-tighter leading-tight break-words">
             {post.topic}
           </h2>
           <p className="text-white/40 font-medium italic">Сгенерировано {new Date(post.createdAt).toLocaleDateString('ru-RU')}</p>
        </section>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
          
          {/* Main Content Area: Slide Grid */}
          <div className="lg:col-span-8 space-y-10">
            <div className="flex items-center justify-between">
               <h3 className="text-2xl font-black flex items-center gap-3">
                  {isCarousel ? <Layout className="h-7 w-7 text-primary" /> : <ImageIcon className="h-7 w-7 text-primary" />}
                  {isCarousel ? "Структура Карусели" : "Ваш Арт"}
               </h3>
               <div className="text-xs font-bold text-white/30 uppercase tracking-widest">
                  {isCarousel ? `${content.length} Слайдов` : "1 Объект"}
               </div>
            </div>

            {isCarousel ? (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 outline-none">
                {content.map((slide: any, i: number) => (
                  <div key={i} className="group relative">
                     <div className="glass rounded-[2.5rem] border-white/5 p-8 flex flex-col h-full relative overflow-hidden transition-all hover:border-primary/20 hover:bg-white/[0.02] shadow-2xl">
                        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-primary/50 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
                        
                        <div className="flex justify-between items-start mb-8">
                           <div className="h-10 w-10 text-xl font-black bg-primary/10 text-primary rounded-xl flex items-center justify-center glow-primary">
                             {i + 1}
                           </div>
                           <button className="h-8 w-8 rounded-lg bg-white/5 flex items-center justify-center hover:bg-white/10 transition-colors opacity-0 group-hover:opacity-100">
                              <Copy className="h-4 w-4 text-white/40" />
                           </button>
                        </div>

                        <div className="flex-1 space-y-6">
                           {slide.imageUrl ? (
                             <div className="w-full aspect-square rounded-2xl overflow-hidden border border-white/10 shadow-xl bg-black/40">
                               <img src={slide.imageUrl} alt={slide.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" />
                             </div>
                           ) : (
                             <div className="w-full aspect-square rounded-2xl bg-white/5 border border-dashed border-white/10 flex flex-col items-center justify-center text-white/20 gap-3">
                                <ImageIcon className="h-8 w-8" />
                                <span className="text-[10px] uppercase font-black tracking-widest italic">No Image</span>
                             </div>
                           )}
                           
                           <h4 className="text-xl font-black tracking-tight leading-snug">
                             {slide.title}
                           </h4>
                           <p className="text-white/50 text-sm font-medium leading-relaxed italic">
                             {slide.content}
                           </p>
                        </div>

                        <div className="mt-8 pt-6 border-t border-white/5">
                           <div className="flex items-center gap-3 text-xs font-black uppercase tracking-widest text-primary/60 italic">
                             <Wand2 className="h-3.5 w-3.5" />
                             Prompt is ready
                           </div>
                        </div>
                     </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="glass rounded-[3.5rem] border-white/5 p-10 md:p-14 space-y-12 shadow-2xl relative overflow-hidden group">
                 <div className="absolute -top-24 -right-24 w-64 h-64 bg-primary/20 rounded-full blur-[120px] pointer-events-none group-hover:bg-primary/30 transition-all duration-1000" />
                 
                 <div className="relative z-10 flex flex-col md:flex-row gap-8 items-center">
                    <div className="h-20 w-20 rounded-[1.5rem] bg-gradient-primary flex items-center justify-center text-white glow-primary rotate-3 transition-transform group-hover:rotate-0">
                      <ImageIcon className="h-10 w-10" />
                    </div>
                    <div className="flex-1 text-center md:text-left">
                       <h3 className="text-3xl font-black tracking-tighter mb-2">Шедевр готов</h3>
                       <p className="text-white/40 font-medium italic">Оцените детали и качество генерации</p>
                    </div>
                 </div>

                 {typeof content[0] === 'object' && content[0].url ? (
                    <div className="w-full relative rounded-3xl overflow-hidden border border-white/10 shadow-2xl z-10 bg-black/40 group/img">
                      <img 
                        src={content[0].url} 
                        alt="Final Art" 
                        className="w-full h-auto object-contain max-h-[800px] transition-transform duration-1000" 
                      />
                      <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover/img:opacity-100 transition-opacity flex items-end p-8">
                         <button className="px-6 py-3 rounded-xl bg-white text-black font-black text-xs uppercase tracking-widest flex items-center gap-3">
                            <Download className="h-4 w-4" />
                            Скачать в 4K
                         </button>
                      </div>
                    </div>
                 ) : null}

                 <div className="relative z-10 p-8 rounded-3xl bg-white/[0.02] border border-white/5 font-mono text-sm text-primary/70 italic group/prompt transition-all hover:bg-white/[0.04]">
                    <div className="flex justify-between items-center mb-4">
                       <span className="text-[10px] uppercase font-black tracking-widest text-white/20">Art Engine Prompt (EN)</span>
                       <button className="h-8 w-8 rounded-lg bg-white/5 hover:bg-white/10 transition-colors flex items-center justify-center">
                          <Copy className="h-3.5 w-3.5" />
                       </button>
                    </div>
                    {typeof content[0] === 'object' ? content[0].prompt : content[0]}
                 </div>
              </div>
            )}
          </div>

          {/* Sidebar Area: Social & Action Cards */}
          <div className="lg:col-span-4 space-y-8">
            
            {/* Caption & Post Description */}
            <div className="glass p-10 rounded-[3.5rem] border-white/5 space-y-8 sticky top-32 shadow-2xl bg-gradient-to-b from-white/[0.02] to-transparent">
              <div className="flex items-center justify-between">
                <h3 className="text-xl font-black flex items-center gap-3">
                  <MessageSquare className="h-5 w-5 text-primary" />
                  Описание поста
                </h3>
                <button className="h-10 w-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center hover:bg-primary/20 transition-all hover:scale-105">
                  <Copy className="h-5 w-5" />
                </button>
              </div>
              
              <div className="p-8 rounded-[2rem] bg-black/50 text-[15px] leading-relaxed whitespace-pre-wrap min-h-[220px] border border-white/5 italic font-medium text-white/70 shadow-inner">
                {post.caption}
              </div>

              <div className="grid grid-cols-2 gap-4">
                 <button className="h-14 rounded-2xl bg-white text-black font-black text-xs uppercase tracking-widest flex items-center justify-center gap-3 transition-all hover:scale-105 active:scale-95 glow-primary">
                    <Share2 className="h-4 w-4" />
                    Поделиться
                 </button>
                 <button className="h-14 rounded-2xl border border-white/10 bg-white/5 font-black text-xs uppercase tracking-widest flex items-center justify-center gap-3 transition-all hover:scale-105 active:scale-95 hover:bg-white/10">
                    <ExternalLink className="h-4 w-4" />
                    Telegram
                 </button>
              </div>

              <div className="pt-8 border-t border-white/5 flex items-center gap-4 group cursor-help">
                 <div className="h-12 w-12 rounded-2xl bg-emerald-500/10 flex items-center justify-center text-emerald-400 group-hover:glow-primary transition-all">
                   <CheckCircle2 className="h-6 w-6" />
                 </div>
                 <div>
                   <p className="text-[10px] font-black uppercase tracking-widest text-emerald-500/60">Content Check</p>
                   <p className="text-sm font-black italic">Готово к публикации</p>
                 </div>
              </div>
            </div>

            <div className="p-8 rounded-[3rem] bg-gradient-to-br from-primary/10 to-transparent border border-white/5 flex flex-col items-center text-center gap-4">
               <div className="text-[10px] font-black text-white/20 uppercase tracking-[0.2em] italic">© mari_lit exclusive</div>
               <p className="text-xs font-medium text-white/50 leading-relaxed italic px-4">
                 Каждая деталь проработана нейросетью по вашему индивидуальному запросу.
               </p>
            </div>
          </div>

        </div>
      </main>
      
      <footer className="py-12 border-t border-white/5 text-center text-[10px] font-black uppercase tracking-[0.2em] text-white/10">
        Picassek Content Studio • Professional Dashboard
      </footer>
    </div>
  );
}
